graph TD
    subgraph "LAN 1 [192.168.1.0/24]"
        PC1[PC 1 - 192.168.1.11] -- LAN Cable --- Hub1{Switching Hub}
        PC2[PC 2 - 192.168.1.12] -- LAN Cable --- Hub1
    end

    subgraph "LAN 2 [192.168.2.0/24]"
        PC3[PC 3 - 192.168.2.11] -- LAN Cable --- Hub2{Switching Hub}
    end

    subgraph Router
        direction LR
        Router_PC[Linux Router] -- NIC 1 --- if1((192.168.1.1))
        Router_PC -- NIC 2 --- if2((192.168.2.1))
    end

    Hub1 --- if1
    Hub2 --- if2

    style PC1 fill:#f9f,stroke:#333,stroke-width:2px
    style PC2 fill:#f9f,stroke:#333,stroke-width:2px
    style PC3 fill:#f9f,stroke:#333,stroke-width:2px
    style Router_PC fill:#ccf,stroke:#333,stroke-width:2px
